In [45]:
import pandas as pd
import numpy as np

In [46]:
nhspi = pd.read_csv('../data/nhspi_2021_domains.csv')

# Converting dataset to year-wise chunks

In [47]:
nhspi_year = []

for year in range (2013,2021):
    nhspi_year.append(nhspi[nhspi['YEAR']==year])

In [48]:
for frame,year in zip(nhspi_year,range (2013,2021)):
    frame.rename({'HSS': f'HSS_{year}',
              'CPE': f'CPE_{year}',
              'IIM': f'IIM_{year}',
              'HD': f'HD_{year}',
              'CM': f'CM_{year}',
              'EOH': f'EOH_{year}'}, axis=1, inplace=True)
    frame.drop(['YEAR'],axis=1,inplace=True)

/tmp/ipykernel_783/1665288106.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.rename({'HSS': f'HSS_{year}',
/tmp/ipykernel_783/1665288106.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.drop(['YEAR'],axis=1,inplace=True)
/tmp/ipykernel_783/1665288106.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.rename({'HSS': f'HSS_{year}',
/tmp/ipykernel_783/1665288106.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.drop(['YEAR'],axis=1,inplace=True)
/tmp/ipykernel_783/1665288106.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.rename({'HSS': f'HSS_{year}',
/tmp/ipykernel_783/1665288106.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.drop(['YEAR'],axis=1,inplace=True)
/tmp/ipykernel_783/1665288106.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.rename({'HSS': f'HSS_{year}',
/tmp/ipykernel_783/1665288106.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.drop(['YEAR'],axis=1,inplace=True)
/tmp/ipykernel_783/1665288106.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.rename({'HSS': f'HSS_{year}',
/tmp/ipykernel_783/1665288106.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.drop(['YEAR'],axis=1,inplace=True)
/tmp/ipykernel_783/1665288106.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.rename({'HSS': f'HSS_{year}',
/tmp/ipykernel_783/1665288106.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.drop(['YEAR'],axis=1,inplace=True)
/tmp/ipykernel_783/1665288106.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.rename({'HSS': f'HSS_{year}',
/tmp/ipykernel_783/1665288106.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.drop(['YEAR'],axis=1,inplace=True)
/tmp/ipykernel_783/1665288106.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.rename({'HSS': f'HSS_{year}',
/tmp/ipykernel_783/1665288106.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame.drop(['YEAR'],axis=1,inplace=True)

In [49]:
main_data = nhspi_year[0]

for target in nhspi_year[1:]:
    
    main_data = pd.merge(main_data, target, on='STATE')

In [50]:
main_data.to_csv('../data/nhspi_2021_domains_processed.csv')

# Checking Correlation with case peak data

In [54]:
case_peak = pd.read_csv('../data/state_peak.csv')

In [55]:
case_peak

,Unnamed: 0,state,peak_dates,peak_properties
0,0,UT,"['2020-11-19', '2021-01-05', '2021-11-05', '20...","[610.0, 2943.0, 2682.0, 1478.0, 1527.0]"
1,1,CO,"['2020-11-22', '2021-11-08', '2021-09-07', '20...","[463.0, 521.0, 4930.0, 1617.0, 1788.0, 2911.0]"
2,2,AR,"['2021-01-06', '2021-08-13', '2020-07-26', '20...","[101.0, 746.0, 2572.0, 194.0, 2186.0]"
3,3,AS,[],[]
4,4,HI,"['2021-08-28', '2020-08-22', '2021-01-08', '20...","[19.0, 224.0, 89.0, 145.0, 103.0, 757.0]"
5,5,AK,"['2021-09-27', '2020-11-29', '2021-04-05', '20...","[10.0, 85.0, 620.0, 163.0, 972.0]"
6,6,TX,"['2021-01-12', '2021-09-03', '2020-07-17', '20...","[8670.0, 4921.0, 20499.0, 1600.0, 16901.0]"
7,7,OK,"['2020-12-29', '2020-11-20', '2021-08-28', '20...","[100.0, 785.0, 3091.0, 3467.0, 2506.0, 694.0]"
8,8,GA,"['2021-01-09', '2021-08-27', '2020-07-24', '20...","[712.0, 3692.0, 8452.0, 1379.0, 8372.0]"
9,9,MA,"['2021-01-08', '2021-04-01', '2020-04-22', '20...","[1994.0, 5411.0, 2090.0, 1766.0]"
10,10,MP,['2021-08-23'],[1.0]
11,11,PR,"['2021-04-15', '2020-12-13', '2021-08-17', '20...","[26.0, 17.0, 319.0, 344.0, 791.0, 870.0, 781.0]"
12,12,KS,"['2020-11-19', '2021-01-03', '2021-09-02', '20...","[231.0, 434.0, 547.0, 2545.0, 2057.0, 232.0, 1..."
13,13,FL,"['2021-08-16', '2021-01-07', '2020-07-16', '20...","[929.0, 10325.0, 13423.0, 5824.0, 20956.0]"
14,14,PW,[],[]
15,15,WV,"['2021-09-15', '2021-01-02', '2021-04-03', '20...","[34.0, 31.0, 125.0, 1339.0, 390.0, 1721.0]"
16,16,NYC,"['2021-01-14', '2020-04-05', '2021-03-20', '20...","[4674.0, 354.0, 5712.0, 3914.0, 1913.0, 1733.0]"
17,17,NM,"['2020-11-24', '2021-11-14', '2021-08-25', '20...","[148.0, 137.0, 278.0, 1984.0, 210.0, 784.0, 12..."
18,18,PA,"['2020-12-12', '2021-10-01', '2021-04-10', '20...","[1423.0, 878.0, 9305.0, 4375.0, 4689.0]"
19,19,IA,"['2020-11-13', '2021-09-17', '2021-01-05', '20...","[434.0, 503.0, 843.0, 3686.0, 1402.0, 516.0, 1..."
20,20,TN,"['2020-12-17', '2021-09-05', '2020-07-24', '20...","[385.0, 2084.0, 7467.0, 1247.0, 7224.0]"
21,21,OH,"['2020-12-08', '2021-09-15', '2021-04-08', '20...","[614.0, 1293.0, 1065.0, 9837.0, 1932.0, 6489.0]"
22,22,RMI,[],[]
23,23,NY,"['2021-01-08', '2020-04-08', '2021-03-31', '20...","[3783.0, 373.0, 9109.0, 3770.0, 3334.0]"
24,24,SD,"['2020-11-11', '2021-09-11', '2021-11-11', '20...","[89.0, 89.0, 1235.0, 185.0, 421.0, 355.0]"
25,25,ND,"['2020-11-10', '2021-10-01', '2021-04-07', '20...","[54.0, 1262.0, 148.0, 571.0]"
26,26,CA,"['2021-01-02', '2021-08-23', '2020-07-19', '20...","[8851.0, 38566.0, 2585.0, 13393.0, 6164.0]"
27,27,IL,"['2020-11-16', '2021-01-03', '2021-09-02', '20...","[2343.0, 2018.0, 10989.0, 6152.0, 3041.0, 3881.0]"
28,28,DE,"['2020-12-12', '2021-01-06', '2021-09-22', '20...","[190.0, 117.0, 740.0, 736.0, 326.0, 450.0]"
29,29,WI,"['2020-11-13', '2021-11-16', '2021-09-27', '20...","[890.0, 6203.0, 2774.0, 825.0, 2910.0, 2921.0]"
30,30,GU,"['2021-09-10', '2020-11-09', '2020-10-19', '20...","[4.0, 4.0, 51.0, 75.0, 79.0, 10.0, 7.0, 7.0, 1..."
31,31,NE,"['2020-11-16', '2021-11-11', '2021-09-08', '20...","[332.0, 276.0, 1962.0, 335.0, 752.0, 810.0]"
32,32,IN,"['2020-12-03', '2021-09-03', '2021-04-13', '20...","[610.0, 918.0, 6158.0, 1074.0, 3884.0]"
33,33,CT,"['2021-01-09', '2020-12-09', '2021-03-31', '20...","[862.0, 119.0, 2309.0, 2347.0, 1155.0, 620.0, ..."
34,34,NV,"['2020-12-08', '2021-01-02', '2021-08-26', '20...","[131.0, 1025.0, 2486.0, 2103.0, 388.0, 1105.0,..."
35,35,NC,"['2021-01-08', '2021-09-02', '2020-07-20', '20...","[1892.0, 1536.0, 7478.0, 1847.0, 6754.0]"
36,36,MO,"['2020-11-13', '2020-12-30', '2021-08-05', '20...","[201.0, 198.0, 4653.0, 3377.0, 635.0, 529.0, 2..."
37,37,MS,"['2021-08-18', '2021-01-02', '2020-07-19', '20...","[1065.0, 2109.0, 229.0, 3180.0]"
38,38,ME,"['2021-01-09', '2021-09-27', '2021-04-15', '20...","[27.0, 41.0, 536.0, 377.0, 517.0]"
39,39,VT,"['2021-11-12', '2021-09-24', '2021-03-31', '20...","[27.0, 7.0, 6.0, 6.0, 95.0, 136.0, 153.0, 175...."
40,40,ID,"['2020-12-05', '2021-09-29', '2020-07-20', '20...","[64.0, 497.0, 1399.0, 301.0, 1250.0]"
41,41,AL,"['2021-08-28', '2021-01-02', '2020-07-21', '20...","[1690.0, 3725.0, 461.0, 656.0, 4082.0, 1150.0]"
42,42,MI,"['2021-04-05', '2020-11-15', '2021-10-11', '20...","[1184.0, 1638.0, 1352.0, 1255.0, 5908.0, 6129...."
43,43,VI,"['2021-08-10', '2020-08-18', '2020-12-11', '20...","[1.0, 25.0, 16.0, 13.0, 9.0, 15.0, 44.0]"
44,44,NH,"['2021-01-07', '2020-12-14', '2021-11-16', '20...","[81.0, 28.0, 751.0, 755.0, 395.0, 507.0, 736.0]"
45,45,MD,"['2021-01-07', '2020-12-09', '2021-04-07', '20...","[993.0, 816.0, 578.0, 2566.0, 2735.0, 1305.0, ..."
46,46,WA,"['2021-09-02', '2020-12-07', '2021-01-06', '20...","[360.0, 805.0, 2720.0, 2398.0, 1357.0, 3306.0]"
47,47,MT,"['2020-11-17', '2021-10-03', '2021-01-06', '20...","[15.0, 115.0, 1052.0, 450.0, 156.0, 888.0]"
48,48,LA,"['2021-08-11', '2021-01-08', '2020-07-20', '20...","[925.0, 1963.0, 3104.0, 472.0, 5026.0]"
49,49,DC,"['2021-01-10', '2020-12-12', '2021-09-15', '20...","[161.0, 68.0, 242.0, 266.0, 133.0, 188.0]"
50,50,NJ,"['2021-01-11', '2020-12-09', '2021-03-27', '20...","[3331.0, 416.0, 5276.0, 5609.0, 4179.0, 2124.0]"
51,51,KY,"['2021-09-02', '2021-01-10', '2020-12-03', '20...","[189.0, 687.0, 3042.0, 3277.0, 549.0, 4327.0]"
52,52,WY,"['2020-11-17', '2021-09-14', '2021-01-09', '20...","[15.0, 43.0, 37.0, 708.0, 282.0, 73.0, 507.0]"
53,53,MN,"['2020-11-20', '2021-11-18', '2021-10-07', '20...","[642.0, 678.0, 714.0, 6065.0, 1920.0, 2705.0, ..."
54,54,FSM,[],[]
55,55,AZ,"['2021-01-08', '2020-07-05', '2021-08-27', '20...","[3312.0, 582.0, 8252.0, 701.0, 3023.0]"
56,56,RI,"['2020-12-06', '2021-01-04', '2021-04-03', '20...","[312.0, 95.0, 1113.0, 973.0, 407.0, 330.0]"
57,57,SC,"['2021-09-02', '2021-01-10', '2020-07-16', '20...","[164.0, 1771.0, 961.0, 4931.0, 4993.0]"
58,58,VA,"['2021-01-14', '2021-09-10', '2021-04-02', '20...","[953.0, 1047.0, 985.0, 5173.0, 1461.0, 3418.0]"
59,59,OR,"['2021-08-27', '2020-12-04', '2021-01-03', '20...","[63.0, 63.0, 324.0, 1365.0, 1097.0, 756.0, 210..."